### PR TITLE
Handle dots in repo. Fixes #2.

### LINKED ISSUE #2: Handle dots in repo
Does not seem to correctly handle dots (periods) in repository name.

### PR DESCRIPTION
**Pull request by adjohnson916**

### CODE REVIEW

**Comment by jonschlinkert** [comment]
good catch! thanks

**Comment by adjohnson916** [comment]
@jonschlinkert If you have time, please release. Or add me as maintainer, and I can do so.

**Comment by jonschlinkert** [comment]
no prob! I've also added you as a maintainer anyway, thanks for the pr

**Comment by jonschlinkert** [comment]
also added you as an npm owner...

**Pull request merged**
