### PR TITLE
add more related

### PR DESCRIPTION
**Pull request by tunnckoCore**

### CODE REVIEW

**Comment by tunnckoCore** [comment]
btw, awful installation time of `verb` (verb-cli) 5min+ on 100mb net.

**Comment by jonschlinkert** [comment]
thanks!

> doh... seems something went wrong in defaults?

ha, yeah that's exactly why I created this library. the current libs that I use for parsing/stringifying github urls return weird results. 

> btw, awful installation time of verb 

must have been npm or something. It installs in a couple seconds for me.

**Comment by jonschlinkert** [comment]
I'll merge this today, I can fix the link too no worries. fwiw I'm going to be pushing up a refactor of verb this week too. it's a lot faster

**Comment by tunnckoCore** [comment]
> must have been npm or something. It installs in a couple seconds for me.

Hmm yea, maybe, all installations are slow today. hmm, lol

> fwiw I'm going to be pushing up a refactor of verb this week too. it's a lot faster

Great. btw, i'm interested in your verb configuration/boilerplate, could you share it?

**Comment by jonschlinkert** [comment]
> i'm interested in your verb configuration/boilerplate, could you share it? Just want to review it

yeah no prob, I just use the one that is generated by [generator-verb](https://github.com/assemble/generator-verb). I'd really like to refactor that generator, it was one of the first generators I did when I knew nothing about the yeoman API. plus the yeoman API has changed a lot since then

**Pull request closed without merging**
